version: '3.5'

services:
  go-slack-bot:
    build:
      context: .
      target: build
    env_file: .env
    volumes:
      - ./:/go/app
    command: realize start --run
    ports:
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
